### ISSUE TITLE
Preprocessing Data

### ISSUE THREAD

**Issue by JBarsotti** [estenhl/pyment-public#13]
I have a bunch of NIFTI files that were skull-stripped. Do I still need to go through the preprocessing steps given in the preprocessing script, or can I feed the images as they are into the neural network for brain age prediction?

**Comment by estenhl** [comment]
Hi! You would still need to perform the subsequent preprocessing steps, e.g. those related to orientation and cropping. Also be aware that the process I use for skullstripping in FreeSurfer performs intensity normalization. In case you are using some other tool for the skullstripping I would ensure you also perform this step somehow

**Comment by JBarsotti** [comment]
Thank you for such a quick reply! I was able to get the steps you used to run (I think), so I will try to use those. I think your paper in NeuroImage is wonderful.

**Comment by estenhl** [comment]
Great, let me know how it goes! Thank you so much :) I will close this issue, but feel free to reopen it or send me an email if it doesn't work out
