### ISSUE TITLE
Feature Importance in Neural Net

### ISSUE THREAD

**Issue by JBarsotti** [estenhl/pyment-public#14]
Hi,

I've gotten your model working, and it is fantastic! Have you done any saliency mapping to see which pixels in the images are most influential on brain age predictions? I am thinking about trying to do it myself, but figured I'd ask first.

Thanks!

**Comment by estenhl** [comment]
Brilliant, glad to hear that! I have been working on explainability for a little while now, mostly in the context of classification based on a similar architecture. We have a preprint available here you can check out: https://www.medrxiv.org/content/10.1101/2023.06.22.23291592v1. My personal favourite among the explainability methods is LRP, which is kind of tricky in the case of a regression model. I am working on a paper on the topic currently, bot nothing is out yet. If you wanna try it yourself I encourage that, I also have som explainability implemented here if thats of interest: https://github.com/estenhl/keras-explainability
