### ISSUE TITLE
How to use your trained model to predict our dataset?

### ISSUE THREAD

**Issue by hping666** [estenhl/pyment-public#16]
Hello,

We'd like to test your trained model on our own datasets. However, I find hard to put our datasets into your data generator. Could you please give some guidance ?

**Comment by estenhl** [comment]
Absolutely! Have you formatted your dataset as in the notebook with the IXI dataset? If so, what errors/troubles are you seeing?

**Comment by estenhl** [comment]
I'll close this as stale for now, but feel free to reopen if necessary
