### ISSUE TITLE
Unable to find pre-trained weights

### ISSUE THREAD

**Issue by amirro1** [estenhl/pyment-public#18]
Hi, 

Thanks for this project. You mention in the readme that users should be able to run a pre-trained model by downloading existing weights. However,  I can't find an example of how these weights are downloaded in the notebooks. Is there an h5 file (or similar) somewhere with the weights that I could access?

Thanks

**Comment by estenhl** [comment]
Sorry for the late reply, there are some google drive urls in the weight repo you can use if you want to download and inject them manually:

https://github.com/estenhl/pyment-public/blob/main/pyment/models/utils/weight_repository.py

I would generally recommend using the built-in functionality when possible though (e.g. weights=... as a parameter to the model class)
