### ISSUE TITLE
Interpreting the ranking and soft classification outputs

### ISSUE THREAD

**Issue by amirro1** [estenhl/pyment-public#19]
Hi, 

Thanks again for this awesome repo. I have run the regression model on some of my data,  and I am now attempting to run the soft classification and ranking models. Since both the soft classification and ranking models have multiple outputs (i.e. 'age bins'), I wrote some simple functions to translate the model output (for a single input image) into an age prediction (I included this code at the end of my post). When I run the models followed by these simple functions, I get reasonable outputs, but I have noticed a few unexpected things: 

1. Both the softmax model and the rank model produce outputs values between 3 and 4 (rather than 0-1). To account for this, I simply subtract three from every entry in the output. Is this extra +3 expected (perhaps because that is the min_age)? Or have I run the models wrong?

2. When I pass a single input image into the softmax model, the output vector has length 93 (I think this is representing the age bins from 3-95). However, the output vectors from the rank model only have length of 91.  Is this expected or does it indicate that I ran the model wrong?
 
3. For my data, the outputs from the rank model tend to be higher than those from the reg and sm model. For both the sm model and the rank model, I add +3 as the min_age (following the equations in the Leonardsen 2022 neuroimage paper). Will the min_age term always be 3? Is it appropriate to add this value, as I have done in the code below? Or am I incorrectly inflating the age predictions

Code for softmax:

```
   # subtract the extra +3 from every entry and ensure we have a valid probability density  
    probability_weight_vector = probability_weight_vector -3
    sum_probs = probability_weight_vector.sum()
    if not math.isclose(sum_probs, 1.0, abs_tol=0.0001):
       raise Exception(f"ERROR: after subtracting 3 from each entry in your probability_weight_vector, the sum was {sum_probs}. However, since this weight vector represents a probability density, we expect the sum to be 1.)
    
    # multiply each probability entry by the associated age 'bucket' (0-92), add 3 and return
    age_vector = np.linspace(0,92, num=93)
    predicted_age = ((age_vector*probability_weight_vector).sum())+3
    return predicted_age 
    
```

Code for rank:
```
    # subtract the extra +3 from every entry and ensure the resulting entries are all valid probabilities (i.e. between 0-1) 
    probability_weight_vector = probability_weight_vector -3
    if not np.all((probability_weight_vector >= 0 )& (probability_weight_vector <=1)):
        raise Exception("Input data to compute_age_from_SFCN_rank function was not formatted as expected. All entries should be between 3 and 4")
    
    # predict age by summing the number of entries for which p>=0.5
    age = np.sum(probability_weight_vector>=0.5)
    return age +3

```

Note: in both code snippets the probability_weight_vector is the output of the model when given a single input image

Sorry for the long message. 

Thanks, 
Amy

**Comment by estenhl** [comment]
Hey Amy, sorry for not replying, I am currently in parental leave and have severely reduced capacity 😅 I can't remember the answers to your questions of the top of my head, but I think I have thought about them sometime before filling my mind with baby-stuff. Will get back to you as soon as I have time, but unfortunately no guarantees for when that will be.

- Esten

**Comment by amirro1** [comment]
No worries! Thanks for the response.

**Comment by estenhl** [comment]
Dear Amy, I apologize again for the long response times. I have now had some time to dig into the questions above. I also applaud you for being the first to use this code (to my best knowledge), and having to navigate some nasty bugs on my side.

1. This is a bug in the models. Subtracting -3 is a good solution
2. This is a combination of a bug and a feature. Where the softmax model has one bin per possible age, the ranking model represents a prediction of 3 with <0.5 prediction in all nodes. Therefore it should have 1 node less. Why it has 2 less is beyond me at the moment, probably a bug (that doesn't have that much effect, as its only impact is to group those with age 94 together with those with age 95). Will update you if I suddenly remember a good reason it is like this
3. What is the age range of the sample you are predicting? The ranking model has worse age biases than the two others, which for me means that the mean prediction varies quite a lot between the datasets I'm using. The min_age term should always be +3

Hopefully this clarifies things somewhat! I'm in the process of reformatting the repo so I will fix some of these things on my end (and provide some postprocessing-functions) in the coming days and weeks.

- Esten

**Comment by amirro1** [comment]
No worries! Thanks so much for the detailed answers. 

1.  Sounds good. 
2. Okay. I will proceed with the method I described above. We don't have anyone nearly in their 90s
3. Our subjects range from 6-20 years. So it is definitely possible that the rank model is just exaggerating the bias where these models tend to overestimate the age of young participants. 
    - I just wanted to double check that large(ish) differences between the three models is 'expected'.
    -  All three models had a good fit to our data (when we plotted actual age vs predicted age from the model, we saw the points cluster nicely around a line with a slope near 1). 
    - However, the age estimations for individual participant's images did tend to vary between the models. For example, it wasn't uncommon for a participant's age to be estimated as 17.5 by one model, 18.8 by one model, and 20 by one model (and similar differences remained after correcting each model's predictions for bias described above)
    - While these estimates were all reasonably close to that participant's true age (and became even closer after bias correction), I was surprised by the magnitude of the difference, given that only the "top" of your model changes between the 3 variations. 
    - Did you notice prediction variations like this between the three model 'versions'?

Thanks again,
Amy

**Comment by estenhl** [comment]
I haven't looked into the relationship between the predictions between these three models specifically, but I have observed quite a lot of variance in the predictions between brain age models in general, even when the architecture is exactly the same but some other aspect of the training process varies. Without having explicitly investigated why this is, my gut feeling would be that it is somehow related to the redundancy of age in the brain. To me this would seem to imply that there are multiple strategies the models can learn that are approximately equal in terms of performance across a dataset, but where predictions from individuals can vary quite a lot depending on the exact strategy. This is only speculation though, if you investigate this further I would be interested in what you discover :)
