### ISSUE TITLE
FreeSurfer Versions conflict

### ISSUE THREAD

**Issue by rafaloz** [estenhl/pyment-public#22]
Hello Dr. Leonardsen,

I am currently working with several BrainAge models, including Pyment. One of these models uses the output from FreeSurfer 6.0 as input. I am curious if the -autorecon1 pipeline is interchangeable between different FreeSurfer versions. My initial assessment suggests that the 5.3 pipeline would be the best for applying your model (https://doi.org/10.1007/s11682-018-9994-x). However, running the preprocessing twice seems inefficient.

Thank you for making your model available to everyone!

Regards,

**Comment by estenhl** [comment]
Hi! I think there might be small differences, but I can't tell you exactly what they are 😬 in my opinion, if the predictions look reasonable (e.g. approx same MAE as I have reported elsewhere) and everyone are processed with the same version on your end I would say that is sufficient. Can't give any hard guarantees though. You could run a couple of subjects with both versions and see if the results are different. Of you do please let me know, I'm also curious :)

**Comment by rafaloz** [comment]
Hello Prof. Leonardsen, 

Ok, I tested both versions of Freesurfer on my data, FreeSurfer 5.3 and FreeSurfer 6.0. My data is weird because the age range is very narrow (18-21 years old, n=252) but it seems better to run the original pipeline of the paper (correlation between v5.3 and 6.0 predictions ~0.8; MAE v5.3 = 2.06; MAE v6.0 = 2.23). I expected a higher correlation > 0.9 :fearful: but I guess you are right, following the same version for all the analysis might be good enough. Not all OS can run freesurfer 5.3. which can be a pain in the ass... but still a great resource to use. 

[ResultsPyment.csv](https://github.com/user-attachments/files/15526528/ResultsPyment.csv)

Thank you!

**Comment by estenhl** [comment]
Hmm, wow, that is a surprisingly low correlation indeed! Would expect it to be higher. But, as you say, when the age range is narrow it sounds reasonable to me that relatively small changes in the preprocessing has more of an impact to the correlation. I still think this would represent random noise and not a bias in any sense in downstream analyses, so you should be fine, but could be less sensitive. I promise next version will have simpler preprocessing! 😅 

And please, just call me Esten, no profs here :) Let me know how it goes!

**Comment by estenhl** [comment]
Has been stale for a month so I'm closing this, let me know if theres still issues to attend
