### ISSUE TITLE
Can't find resources (data/*csv) when installing via github and running scripts/prediction.py

### ISSUE THREAD

**Issue by RDoerfel** [estenhl/pyment-public#24]
Hi Esten, 

Quite a lot has happened here since I last visited. Very nice! 

I've been running into the issue that Python can't find the CSV files you placed in `data/.`  I assume the issue is that the data files don't get distributed when installing it as a package. So when Python is looking for the data folder [here](https://github.com/estenhl/pyment-public/blob/e0613c5212f6b7aa8dff57a1dcdc381299d0c5fb/pyment/utils.py#L6), it can't find them. 

I've been creating a clean new environment and installed your package via github:
```shell
conda create --name pyment python=3.9
pip install git+https://github.com/estenhl/pyment-public
```

A potential solution would be to move essential resource files into the package itself:
```
pyment-public/
├── ...
├── pyment/
│   ├── __init__.py
│   ├── data/
```
And add the following to your ´setup.py´:
```
package_data={
    'pyment': ['data/*.csv'],
}
```
You can then access the data files via:

``` python
import pkg_resources
models_file = pkg_resources.resource_filename('pyment', 'data/models.csv')
```
as you potentially would like to do [here](https://github.com/estenhl/pyment-public/blob/e0613c5212f6b7aa8dff57a1dcdc381299d0c5fb/pyment/models/weight_repository/weight_repository.py#L72).

**Comment by estenhl** [comment]
@RDoerfel thanks again for pointing this out, can you check whether #26 solves it? I think I ended up with what you suggested, although I took a detour to try to avoid putting the data-files inside the Python package :p

**Comment by RDoerfel** [comment]
Sure, I'll have a look!

**Comment by RDoerfel** [comment]
An alternative would be to have a config directory in your package and only add the information that is really required for configurations. I think there is a lot of stuff in the data directory that is not necessary for the actual package itself? 

One could, for example, have the following config file for the models:

pyment/config/models.yaml
```yaml
brain-age-2022:
  RegressionSFCN: 
    filename: blabla
   sh: sometingsomething
  RankingSFCN:
    filename: blablub
    sh: somehtingelse
dementia-2024-fold-0:
...
```
When you read it, you get a dict "models" that you could use as follows:

```python
model = "brain-age-2022"
architecture = "RegressionSFCN"

models = read_yaml("pyment/config/models.yaml")
filename = models[model][architecture ]['filename']
sh = models[model][architecture ]['sh']
```

**Comment by RDoerfel** [comment]
But let's leave this for the future: #26 closed the raised initial issue. Thanks!
