### ISSUE TITLE
Help with installation

### ISSUE THREAD

**Issue by jmdk73** [estenhl/pyment-public#27]
Hi,

I am struggling to get pyment working on our system. We managed last year, but after some system updates, it no longer works.

I tried from the beginning using pip install in a new conda environment but the public directory can't be copied. 

I get this warning when installing the prerequisites:

Defaulting to user installation because normal site-packages is not writeable
WARNING: Skipping /usr/local/fsl6.0.7/lib/python3.11/site-packages/nlopt-2.7.1.dist-info due to invalid metadata entry 'name

Using the public directory that did work last year, I get a lot of errors using pytest tests:

ImportError: cannot import name 'get' from 'pyment.models'
ModuleNotFoundError: No module named 'pyment.utils.decorators'; 'pyment.utils' is not a package
ModuleNotFoundError: No module named 'pyment.labels'

And it goes on eding with:

ERROR tests/test_async_nifti_generator.py
ERROR tests/test_binary_label.py
ERROR tests/test_categorical_label.py
ERROR tests/test_classwise_metrics.py
ERROR tests/test_continuous_variable.py
ERROR tests/test_cyclical_learning_rate.py
ERROR tests/test_find_latest_weights.py
ERROR tests/test_get_model.py
ERROR tests/test_json_serialize.py
ERROR tests/test_labels.py
ERROR tests/test_learning_rate_schedule.py
ERROR tests/test_multisample_dataset.py
ERROR tests/test_nifti_augmenter.py
ERROR tests/test_nifti_dataset.py
ERROR tests/test_nifti_generator.py
ERROR tests/test_nifti_preprocessor.py
ERROR tests/test_ordinal_label.py
ERROR tests/test_preprocessing_crop.py
ERROR tests/test_preprocessing_freesurfer.py
ERROR tests/test_preprocessing_fsl.py
ERROR tests/test_resetter.py
ERROR tests/test_single_domain_async_nifti_generator.py
ERROR tests/test_vgg11.py

Any ideas?

Kind regards,
Julian

**Comment by estenhl** [comment]
Hi Julian! 

Let see here...
The warning don't look that bad, so I would overlook those. From the names etc it seems like you are trying to get the old version of the repo working? Have you tried to install the new one as it is now?

**Comment by jmdk73** [comment]
Yes, pip install installs the prerequisites but doesn't seem to copy the public directory.

When trying git clone:

git clone git@github.com:estenhl/pyment-public.git
Cloning into 'pyment-public'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

**Comment by estenhl** [comment]
Hm, that is strange. Can you try cloning with the http-address?

git clone https://github.com/estenhl/pyment-public.git

**Comment by jmdk73** [comment]
Thanks, that work better! pytest gives no errors anymore.

I do have to say I don't know how to use it though. Last version I had a wrapper made by RDorfel, but that no longer works.

**Comment by estenhl** [comment]
Good to hear!

You could start by clicking your way through these tutorials:
1. https://github.com/estenhl/pyment-public/blob/main/notebooks/Download%20and%20preprocess%20IXI%20T1%20data.ipynb
2. https://github.com/estenhl/pyment-public/blob/main/notebooks/Predict%20brain%20age.ipynb

From there, you should hopefully have a grasp on how to preprocess your own data (from the first notebook), and with slight modifications the second notebook should be usable to procure predictions for it. Let me know how it goes, and either post an issue here or send me an email at estenhl@uio.no if you're not able to get it working!
