### ISSUE TITLE
Installation: Add requirements to setup.py

### ISSUE THREAD

**Issue by RDoerfel** [estenhl/pyment-public#8]
Hey,

to make the installation more straightforward, it would be possible to add the requirements to the `setup.py` ([See Here](https://packaging.python.org/en/latest/discussions/install-requires-vs-requirements/#:~:text=install_requires%20is%20a%20setuptools%20setup,used%20to%20install%20its%20dependencies.&text=Additionally%2C%20it%27s%20best%20practice%20to,known%20lower%20or%20upper%20bounds.))

This would allow doing something like:

`pip install git+https://github.com/estenhl/pyment-public`

and would therefore allow a much easier installation :)

If this sounds like something you would like, I could work on that and open a PR once I'm ready!

**Comment by estenhl** [comment]
Good suggestion, if you want to do it @RDoerfel that would be awesome :)

**Comment by RDoerfel** [comment]
Great, I'll see what I can do :)

**Comment by estenhl** [comment]
Sorry for not being responsive @RDoerfel, I had the github-account linked to an old email. On the most stubborn system I am using the tensorflow version is 2.6, and it is a pain to upgrade it there, so if you can aim for that that would be awesome

**Comment by RDoerfel** [comment]
No worries, I was on vacation anyway :)

**Comment by estenhl** [comment]
Modified the setup.py, hope you haven't been stuck on tensorflow versioning since this was opened @RDoerfel

**Comment by RDoerfel** [comment]
That is very cool. Thank you! I had some issues with testing the installation and then constantly kept forgetting about it.
